# Generated by Django 5.0.1 on 2024-05-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menuitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
