# Generated by Django 5.0.1 on 2024-05-14 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0002_menuitems_delete_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitems',
            old_name='course',
            new_name='courses',
        ),
    ]
